---

drupal:
  build: .
  ports:
    - "8080:80"
  links:
    - database

database:
  environment:
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: dbpass
    MYSQL_DATABASE: drupal
    MYSQL_ROOT_PASSWORD: root
  image: mariadb:10.1.16
