
version: '2'

networks:
  zanthia:



services:
  git:
    build: docker/zanthia/git
    ports:
      - "22222:22"
    volumes:
    #  - ./docker/zanthia/git/app:/var/git/app
      - /var/run/docker.sock:/tmp/docker.sock
      - ./shared:/zanthia-shared
    expose:
      - "22222"
    env_file:
      - zanthia.env
    networks:
      - zanthia

  proxy:
    build: docker/zanthia/proxy
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - zanthia.env
    networks:
      - zanthia

  rest:
    build: docker/zanthia/rest
    links:
      - git
    volumes:
    #  - ./docker/zanthia/rest/app:/srv/rest-server/app
      - /var/run/docker.sock:/tmp/docker.sock
      - ./shared:/zanthia-shared
    env_file:
      - zanthia.env
    volumes_from:
      - proxy:rw
    networks:
      - zanthia
    depends_on:
      - git
      - proxy
