

version: '2'
services:
  listener:
    build: docker/listener
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - .:/app
    expose:
      - "2222"

# version: '2'
# services:
#   nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       - "80:80"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro

#   whoami:
#     image: jwilder/whoami
#     container_name: whoami
#     environment:
#       - VIRTUAL_HOST=whoami.local
