

version: '2'
services:
  git:
    build: docker/git
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - .:/app
    expose:
      - "2222"

  rest:
    build: docker/rest
    links:
      - git
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - .:/app
    # To enable "live" development of the app codebase,
    # uncomment the line below.
      - ./docker/rest/app:/var/zanthia/app
    ports:
      - "9999:8888"
    environment:
      - GIT_SSH_COMMAND=ssh -i /app/git_rsa
    # expose:
    #   - "8888"

# version: '2'
# services:
#   nginx-proxy:
#     image: jwilder/nginx-proxy
#     container_name: nginx-proxy
#     ports:
#       - "80:80"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro

#   whoami:
#     image: jwilder/whoami
#     container_name: whoami
#     environment:
#       - VIRTUAL_HOST=whoami.local
