
version: '2'

services:
  git:
    build: docker/zanthia/git
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./shared:/zanthia-shared
    expose:
      - "2222"

  proxy:
    build: docker/zanthia/proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "80:80"
      - "443:443"
    restart: always

  rest:
    build: docker/zanthia/rest
    links:
      - git
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./shared:/zanthia-shared
      - ./docker/zanthia/rest/app:/srv/rest-server/app
    volumes_from:
      - proxy:rw
    # To enable "live" development of the app codebase,
    # uncomment the line below.


    # expose:
    #   - "8888"

  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./certs:/etc/nginx/certs:ro
  #     - /etc/nginx/vhost.d
  #     - /usr/share/nginx/html
  #     - /var/run/docker.sock:/tmp/docker.sock:ro

  # nginx-proxy-ssl:
  #   image: jrcs/letsencrypt-nginx-proxy-companion
  #   container_name: nginx-proxy-ssl
  #   volumes_from:
  #     - nginx-proxy
  #   volumes:
  #     - ./certs:/etc/nginx/certs:rw
  #     - /var/run/docker.sock:/var/run/docker.sock:ro


#   whoami:
#     image: jwilder/whoami
#     container_name: whoami
#     environment:
#       - VIRTUAL_HOST=whoami.local
